pom.xml
src/main/java/com/adicse/comercial/ComercialApplication.java
src/main/java/com/adicse/comercial/controller/TipodocumentoController.java
src/main/java/com/adicse/comercial/dao/INumeradorDao.java
src/main/java/com/adicse/comercial/service/TipodocumentoService.java

Documentos y numeracion

---

src/main/java/com/adicse/comercial/controller/UsuarioResController.java

UsuarioRes BackEnd 24/08/2018

---

src/main/java/com/adicse/comercial/model/Almacen.java
src/main/java/com/adicse/comercial/model/Filial.java
src/main/java/com/adicse/comercial/model/Usuario.java

actualizacion ..... de modelo de usuario

actualiza modelo de usuario

---

src/main/java/com/adicse/comercial/controller/AlmacenController.java
src/main/java/com/adicse/comercial/dao/IAlmacenDao.java
src/main/java/com/adicse/comercial/service/AlmacenService.java

modifica controlador para tomar almacenes por filial

modifica controlador para tomar almacenes por filial

---

src/main/java/com/adicse/comercial/controller/UsuarioController.java

se modifico controller de usuario agregando la filial

se modifico controller de usuario agregando la filial

---

src/main/java/com/adicse/comercial/controller/UsuarioResController.java
src/main/java/com/adicse/comercial/dao/IUsuarioDao.java
src/main/java/com/adicse/comercial/service/UsuarioService.java

backend usuario act 27-08-2018

backend usuario act 27-08-2018

---

src/main/java/com/adicse/comercial/controller/PerfilController.java
src/main/java/com/adicse/comercial/controller/TipodocumentoController.java
src/main/java/com/adicse/comercial/dao/ITipodocumentoDao.java
src/main/java/com/adicse/comercial/service/TipodocumentoService.java

Actualizacion del perfil controler
Creacion del control TipoDocumento que funciona con el TipodocumentoController

Perfil Controller, Tipo Documento

---

src/main/java/com/adicse/comercial/controller/ProductoController.java
src/main/java/com/adicse/comercial/controller/ProveedorclienteController.java
src/main/java/com/adicse/comercial/dao/IProductoDao.java
src/main/java/com/adicse/comercial/dao/IProveedorclienteDao.java
src/main/java/com/adicse/comercial/model/Producto.java
src/main/java/com/adicse/comercial/service/ProductoService.java
src/main/java/com/adicse/comercial/service/ProveedorclienteService.java

Componente codigo de barras
Buscar por dni
Buscar por ruc

Componentes

---

src/main/java/com/adicse/comercial/controller/MedioPagoController.java
src/main/java/com/adicse/comercial/controller/ProductoController.java
src/main/java/com/adicse/comercial/controller/StockactualController.java
src/main/java/com/adicse/comercial/dao/IMedioPagoDao.java
src/main/java/com/adicse/comercial/dao/IProductoDao.java
src/main/java/com/adicse/comercial/dao/IStockactualDao.java
src/main/java/com/adicse/comercial/model/MedioPago.java
src/main/java/com/adicse/comercial/service/MedioPagoService.java
src/main/java/com/adicse/comercial/service/ProductoService.java
src/main/java/com/adicse/comercial/service/StockactualService.java

Control producto y medio de pago

Componentes4

---

src/main/java/com/adicse/comercial/controller/ProductoController.java
src/main/java/com/adicse/comercial/controller/StockactualController.java
src/main/java/com/adicse/comercial/dao/IProductoDao.java
src/main/java/com/adicse/comercial/dao/IStockactualDao.java
src/main/java/com/adicse/comercial/service/StockactualService.java

Componentes5.1

---

md.sql
src/main/java/com/adicse/comercial/dao/IStockactualDao.java

md.sql 
datos para probar los componentes de busqueda

Componentes 5.1 + sql

---

src/main/java/com/adicse/comercial/dao/IIng001Dao.java
src/main/java/com/adicse/comercial/service/Ing001Service.java

actualizacion paginacion ing001

Actulizacion paginacion de ingreso 001

---

src/main/java/com/adicse/comercial/controller/EmpleadoController.java
src/main/java/com/adicse/comercial/dao/IEmpleadoDao.java
src/main/java/com/adicse/comercial/service/EmpleadoService.java

Componente empleado

---

src/main/java/com/adicse/comercial/controller/PeriodoalmacenController.java
src/main/java/com/adicse/comercial/service/PeriodoalmacenService.java

ComponentePeriodoAlmacen

---

src/main/java/com/adicse/comercial/service/ProveedorclienteService.java

Proveedor Cliente Service

---

src/main/java/com/adicse/comercial/controller/Ing001Controller.java
src/main/java/com/adicse/comercial/controller/ProductoController.java
src/main/java/com/adicse/comercial/dao/IStockactualDao.java
src/main/java/com/adicse/comercial/service/StockactualService.java

Nota  de Ingreso

---

src/main/java/com/adicse/comercial/config/auth/service/JWTServiceImpl.java

Se aumento :
claims.put("cntCambioClave", usuario.getCntCambioClave() );
para obtener el contador cambio clave

UsuarioPasswordInit

---

src/main/java/com/adicse/comercial/controller/AlmacenController.java

Actulizacion verificacion

---

src/main/java/com/adicse/comercial/controller/GuiaRemision001Controller.java

se actuliza impresion de guias

se actuliza impresion de guias

---

src/main/resources/reportes/Blank_A4.jrxml

ConfiguracionGuiasLy

---

src/main/java/com/adicse/comercial/controller/Salida001Controller.java
src/main/java/com/adicse/comercial/dao/ISalida001Dao.java
src/main/java/com/adicse/comercial/service/Salida001Service.java

NotaSalida1.1

---

src/main/java/com/adicse/comercial/ComercialApplication.java
src/main/java/com/adicse/comercial/controller/EmpleadoController.java
src/main/resources/application.properties

Actulizacion

---

src/main/java/com/adicse/comercial/utilitarios/UploadTxtComprobante.java

Subir archivos txt comprobante

Subir archivos txt comprobante
